### PR TITLE
Updated flow diagram

### PR DESCRIPTION
**Pull request by mig5**
The [older flow diagram](https://github.com/freedomofpress/securedrop-workstation-ci/raw/main/SD_Qubes_CI.png) currently featured on the README.md is very colorful and tries to depict protocols and sequence order, but is perhaps not laid out in the best way. For example, things like sd-dev, dom0, ws-ci-bastion appear multiple times but are really the same thing each time.

I thought I'd do a proper flow diagram to see if that helps aid in understanding the way it works.

I'd be especially interested in hearing if @legoktm (or anyone else on SD team) finds this a bit more illuminating than the original, which I haven't removed, but have replaced in the README as the image.

### CODE REVIEW

**Comment by legoktm** [comment]
This is great @mig5, definitely an improvement. Some questions from looking at it:

* nightlies are triggered via cron on the ws-ci bastion right? (that was my understanding from https://github.com/freedomofpress/infrastructure/pull/4678)
* based on the lines, am I correct in understanding that sd-dev has the necessary github credentials to update the status? 
* is the bastion fetching the log from dom0 or dom0 pushing it to the bastion? the text says the former but the arrow points to the latter

P.S. curious if there's a text version of the diagram we can save/commit for future edits? At Wikimedia we use [diagrams.net/drawio](https://wikitech.wikimedia.org/wiki/MediaWiki_Engineering/Guides/diagrams.net_conventions) which lets you export to a text/editable version as well.

**Comment by mig5** [comment]
@legoktm 

>     * nightlies are triggered via cron on the ws-ci bastion right?

Correct. In this flow diagram, I'm only showing a typical 'webhook' payload delivered from Github from having pushed a commit. But the flow is very similar otherwise - the only real difference is that nightlies.py learns the latest commit hash from inspecting HEAD directly rather than rely on receiving it from a webhook.

>     * based on the lines, am I correct in understanding that sd-dev has the necessary github credentials to update the status?

Correct. Specifically, the bastion drops a PAT into sd-dev after booting it up. See [this bit of the `update.py` script](https://github.com/freedomofpress/securedrop-workstation-ci/blob/main/sd-dev/bin/status.py#L54-L59) that runs in sd-dev. That file is dropped in via bastion->VMware API->dom0->sd-dev during boot [here](https://github.com/freedomofpress/securedrop-workstation-ci/blob/main/run.py#L247-L252) and [here](https://github.com/freedomofpress/securedrop-workstation-ci/blob/main/run.py#L281).

>     * is the bastion fetching the log from dom0 or dom0 pushing it to the bastion? the text says the former but the arrow points to the latter

Sorry, it's hard to represent on the doc. The bastion uses VMware API (and vmtoolsd daemon running on the dom0) to 'pull' the file off of dom0 onto the bastion - think a file transfer from guest via the VMware API backplane. The dom0 never pushes anything to the bastion. Happens [here](https://github.com/freedomofpress/securedrop-workstation-ci/blob/main/run.py#L337-L340)


> P.S. curious if there's a text version of the diagram we can save/commit for future edits? At Wikimedia we use [diagrams.net/drawio](https://wikitech.wikimedia.org/wiki/MediaWiki_Engineering/Guides/diagrams.net_conventions) which lets you export to a text/editable version as well.

Good question. I used websequencediagrams.com, I'll see if I can export an alternate format.

**Comment by mig5** [comment]
@legoktm I rewrote the diagram using drawio. The .png and the raw/text file is in the branch now. Thanks for the tip.

**Comment by eloquence** [comment]
Per previous approval.

**Pull request merged**
